# -*- coding: utf-8 -*-
"""applstock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RI1HLrrCgoZH57nh9iy-QlO2dGvFu1au
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



# 1. Load data
df = pd.read_csv("/content/drive/MyDrive/AAPL.csv")
df

# 2. Understand data
print(df.head())

print(df.shape)

print(df.info())

# 4. Check missing values
print(df.isnull().sum())

df = df.dropna()

df = df.dropna()

# 4. Check missing values
print(df.isnull().sum())

df = df.dropna()

# 5. Remove duplicates
df = df.drop_duplicates()
df

# 10. Volume analysis

average_volume = df["Volume"].mean()
maximum_volume = df["Volume"].max()
minimum_volume = df["Volume"].min()

print("Average Volume:", average_volume)
print("Maximum Volume:", maximum_volume)

"""## Analyze the stock prices"""

# Resample to monthly average of 'Close' price
monthly_avg_close = df['Close'].resample('ME').mean()

display(monthly_avg_close.head())

# Plotting the monthly average close price
plt.figure(figsize=(12, 6))
monthly_avg_close.plot(title='Monthly Average Close Price')
plt.xlabel('Date')
plt.ylabel('Average Close Price')
plt.grid(True)
plt.show()

# Calculate daily price change
df['Daily_Change'] = df['Close'] - df['Open']

# Display the first few rows with the new column
display(df.head())

# Calculate 10-day highest positive price change
# First, set negative daily changes to 0 to only consider positive changes
df['Positive_Daily_Change'] = df['Daily_Change'].apply(lambda x: x if x > 0 else 0)

# Then, calculate the rolling 10-day maximum of these positive changes
df['10_day_Highest_Positive_Price_Change'] = df['Positive_Daily_Change'].rolling(window=10).max()

print("Displaying DataFrame head with 'Daily_Change', 'Positive_Daily_Change', and '10_day_Highest_Positive_Price_Change' columns:")
# Display the first few rows with the new column
display(df.head(15))

df['Daily_Percentage_Return'] = (df['Daily_Change'] / df['Open']) * 100
display(df.head())

# Convert 'Date' column to datetime if it hasn't been already
# df['Date'] is currently of type object, so explicit conversion is needed.
df['Date'] = pd.to_datetime(df['Date'])

# Define a threshold for anomalous daily percentage return
# For example, considering days with an absolute daily return greater than 5% as anomalous.
return_threshold = 5.0

# Identify anomalous days based on the threshold
anomalous_days = df[abs(df['Daily_Percentage_Return']) > return_threshold].copy()

# Select and rename columns to match the expected output in the next cell
anomalous_days = anomalous_days.rename(columns={
    'Date': 'date',
    'Open': 'open',
    'Close': 'close',
    'Daily_Change': 'Daily_Delta', # Mapping 'Daily_Change' to 'Daily_Delta'
    'Daily_Percentage_Return': 'Daily_Return', # Mapping 'Daily_Percentage_Return' to 'Daily_Return'
    'Volume': 'volume'
})

display(anomalous_days.head())

print("\nAnomalous Trading Days:")
print(
    anomalous_days[
        [
            "date",
            "open",
            "close",
            "Daily_Delta",
            "Daily_Return",
            "volume"
        ]
    ]
)

"""### Biggest Loss and Top 10 Losses"""

# Find the biggest loss day
biggest_loss_day = df.loc[df['Daily_Percentage_Return'].idxmin()]
print(f"Date with Biggest Loss: {biggest_loss_day['Date'].strftime('%Y-%m-%d')}")
print(f"Biggest Loss Percentage: {biggest_loss_day['Daily_Percentage_Return']:.2f}%")

# Get the top 10 loss days (most negative Daily_Percentage_Return)
top_10_losses = df.sort_values(by='Daily_Percentage_Return', ascending=True).head(10)

# Plotting the top 10 loss days
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(12, 6))
sns.barplot(x=top_10_losses['Date'].dt.strftime('%Y-%m-%d'), y=top_10_losses['Daily_Percentage_Return'], hue=top_10_losses['Date'].dt.strftime('%Y-%m-%d'), palette='viridis', legend=False)
plt.title('Top 10 Biggest Daily Percentage Losses')
plt.xlabel('Date')
plt.ylabel('Daily Percentage Return (%)')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

