# -*- coding: utf-8 -*-
"""week4 DV assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lgYhJvGk5fFISv-Jr0UwsRKwMYzo9dh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Load data
df = pd.read_csv("/content/drive/MyDrive/file/shopify_stock.csv")
df

# 1 (2). Understand data
print(df.head())

# 2. Data Visualization: Shopify Closing Price Over Time

plt.plot(df['close'])
plt.title('Shopify Closing Price Over Time')
plt.xlabel('Days')
plt.ylabel('Closing Price')
plt.show()

# 3. Calculate and Plot Moving Averages

# Calculate the 20-day Simple Moving Average (SMA)
df['SMA_20'] = df['close'].rolling(window=20).mean()

# Calculate the 50-day Simple Moving Average (SMA)
df['SMA_50'] = df['close'].rolling(window=50).mean()

# Plot the closing price and moving averages
plt.figure(figsize=(15, 7))
plt.plot(df['date'], df['close'], label='Closing Price', color='blue', alpha=0.7)
plt.plot(df['date'], df['SMA_20'], label='20-Day SMA', color='red', linestyle='--')
plt.plot(df['date'], df['SMA_50'], label='50-Day SMA', color='green', linestyle='--')

plt.title('Shopify Stock Closing Price with 20-Day and 50-Day Moving Averages Over Time')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.show()

# 4. Calculate and Plot Daily Returns

# Calculate daily returns
df['Daily_Return'] = df['close'].pct_change() * 100 # Express as percentage

# Drop the first NaN value resulting from pct_change()
daily_returns = df['Daily_Return'].dropna()

# Create a figure with two subplots
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(18, 6))

# Plot 1: Histogram of Daily Returns
axes[0].hist(daily_returns, bins=50, edgecolor='black', alpha=0.7)
axes[0].set_title('Histogram of Shopify Daily Returns')
axes[0].set_xlabel('Daily Return (%)')
axes[0].set_ylabel('Frequency')
axes[0].grid(axis='y', linestyle='--', alpha=0.7)

# Plot 2: KDE Plot of Daily Returns
import seaborn as sns # Ensure seaborn is imported
sns.kdeplot(daily_returns, fill=True, ax=axes[1])
axes[1].set_title('KDE Plot of Shopify Daily Returns')
axes[1].set_xlabel('Daily Return (%)')
axes[1].set_ylabel('Density')
axes[1].grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

