# -*- coding: utf-8 -*-
"""healthcare (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJdSyVsg5UCOscc5yLVRlonG2oN1q0xw
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df =pd.read_csv("/content/drive/MyDrive/file/healthcare_dataset (1).csv")
df.head()

df.info()

df.isnull().sum()



billing = df.groupby("Medical Condition")["Billing Amount"].sum()
billing

# Group by 'Medical Condition' and 'Gender' and sum 'Billing Amount'
billing_by_gender = df.groupby(['Medical Condition', 'Gender'])['Billing Amount'].sum().unstack()
billing_by_gender

billing.plot(
    kind="bar",
    stacked=True,
    figsize=(10, 6)
)
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.title("Billing Amount by Medical Condition and Insurance Provider")
plt.xticks(rotation=45)
plt.legend(title="Insurance Provider")
plt.show()

# Convert date columns to datetime objects
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

# Calculate Hospital_Stays in days
df['Hospital_Stays'] = (df['Discharge Date'] - df['Date of Admission']).dt.days

# Display the first few rows with the new column
display(df[['Date of Admission', 'Discharge Date', 'Hospital_Stays']].head())

plt.figure(figsize=(10, 6))
sns.violinplot(
    x="Medical Condition",
    y="Hospital_Stays",
    data=df,
)
plt.title("Distribution of Hospital Stays by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Hospital Stays (Days)")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()